### ISSUE TITLE
link to play store doesn't work anymore

### ISSUE THREAD

**Issue by silberzwiebel** [Stolpersteine/stolpersteine-android#13]
The links to the play store, both, in the github readme and, potentially more harmful, the link on the [code for germany homepage](https://codefor.de/projekte/2014-04-30-stolpersteine-app.html) don't work anymore. Since this project is in this year's adventskalender, you might want to fix this soon: https://twitter.com/Kanassido/status/1072803414315286528

**Comment by choefele** [comment]
Thanks for letting me know. Turns out the app was disabled because of a missing setting in the Google Play Store. If fixed this issue and assume the links will start working again

**Comment by silberzwiebel** [comment]
Thanks, works again!
